
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./vizsgaremek_frontend/dist:/usr/share/nginx/html
    depends_on:
      - web
      - backend
    networks:
      - nest_network

  backend:
    env_file: .env.prod
    ports: []
    depends_on:
      - seq
  web:
    env_file: .env.prod
    networks:
      - nest_network
    ports: 
      - "3030:3030"

  # web: 
  #   image: node:alpine # vagy b치rmilyen dummy image, ha csak Nginx szolg치lja ki
  #   entrypoint: echo "frontend handled by nginx"
  #   networks:
  #     - nest_network

  db_backup:
    image: mysql
    container_name: mysql_backup
    depends_on:
      - db
    volumes:
      - ./mysql_backups:/backup
    networks:
      - nest_network  
    environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    entrypoint: >
      bash -c "
        until mysqladmin ping -h db -u root --password= --silent; do
          echo 'V치rakoz치s a database indulasara...';
          sleep 5;
        done;
        while true; do
          TIMESTAMP=$(date +%F_%T);
          mysqldump -h db -u root --password= vizsgadb > /backup/db_$${TIMESTAMP}.sql;
          echo Backup created at $${TIMESTAMP};
          sleep 86400;
        done";
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    ports: 
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    networks:
      - nest_network
  



networks:
  nest_network:
    external: false
