
services:
  nginx:
    image: nginx:1.27.5-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./vizsgaremek_frontend/dist:/usr/share/nginx/html
    depends_on:
      # - web
      - backend
    networks:
      - nest_network

  backend:
    build: ./VizsgaRemek_BackEnd
    container_name: nest_app
    restart: always
    env_file: .env.prod
    depends_on:
      - db
      - seq
    networks:
      - nest_network
  
  # web:
  #   build: ./vizsgaremek_frontend
  #   environment:
  #     NODE_ENV: prod
  #   env_file: .env.prod
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend
  #   networks:
  #     - nest_network

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: vizsgadb
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    ports:
      - "3306:3306"
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d/
      -  mysql_data_prod:/var/lib/mysql

    networks:
      - nest_network
  
  db_backup:
    image: mysql:latest
    container_name: mysql_backup
    depends_on:
      - db
    volumes:
      - ./mysql_backups:/backup
    networks:
      - nest_network  
    environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    entrypoint: >
      bash -c "
        until mysqladmin ping -h db -u root --password= --silent; do
          echo 'Várakozás a database indulasara...';
          sleep 5;
        done;
        while true; do
          TIMESTAMP=$(date +%F_%T);
          mysqldump -h db -u root --password= vizsgadb > /backup/db_$${TIMESTAMP}.sql;
          echo Backup created at $${TIMESTAMP};
          sleep 86400;
        done";
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    ports: 
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    networks:
      - nest_network
  
volumes:
  mysql_data_prod:


networks:
  nest_network:
    external: false
